// <auto-generated />
using System;
using DataBasePomelo;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataBasePomelo.Migrations
{
    [DbContext(typeof(ErrorsDbContext))]
    [Migration("20240811131019_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DataBasePomelo.Models.EnumsErrorsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("EnumeErrors");
                });

            modelBuilder.Entity("DataBasePomelo.Models.ErrorsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("EnumsErrorsId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("EnumsErrorsId");

                    b.ToTable("Errors");
                });

            modelBuilder.Entity("DataBasePomelo.Models.ErrorsEntity", b =>
                {
                    b.HasOne("DataBasePomelo.Models.EnumsErrorsEntity", "EnumsErrors")
                        .WithMany()
                        .HasForeignKey("EnumsErrorsId");

                    b.Navigation("EnumsErrors");
                });
#pragma warning restore 612, 618
        }
    }
}
